on:
  repository_dispatch:
    types: [publish]
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install callum-oakley/tap/jsq
      - run: |
          export name='${{ github.event.client_payload.name }}'
          export version='${{ github.event.client_payload.version }}'
          export description='${{ github.event.client_payload.description }}'
          export depends_on='${{ github.event.client_payload.depends_on }}'
          export repo="https://github.com/callum-oakley/${name}"
          for os in {macos,linux}; do            
            export "${os}_sha256=$(
              curl -sfL "${repo}/releases/download/v${version}/${name}-${version}-${os}.tar.gz" |
                shasum -a 256 | jsq '$.match(/[0-9a-f]{64}/)[0]'
            )"
          done
          cat template | jsq '
            $.replaceAll(
              "{{class}}", $name.charAt(0).toUpperCase() + $name.substring(1),
            ).replaceAll(
              "{{version}}", $version,
            ).replaceAll(
              "{{desc}}", $description,
            ).replaceAll(
              "{{homepage}}", $repo,
            ).replaceAll(
              "{{name}}", $name,
            ).replaceAll(
              "{{macos_sha256}}", $macos_sha256,
            ).replaceAll(
              "{{linux_sha256}}", $linux_sha256,
            ).replaceAll(
              "{{depends_on}}",
              $depends_on ? $depends_on.split(",").map(a => `\n  depends_on "${a}"`).join() : "",
            )
          ' > "${name}.rb"
          git config --global user.name 'Callum Oakley'
          git config --global user.email 'hello@callumoakley.net'
          git add .
          git commit -m "${name} ${version}"
          git push
