on:
  repository_dispatch:
    types: [publish]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install jfn
      - run: |
          version=${{ github.event.client_payload.version }}
          macos_sha256="$(
            curl -sfL "https://github.com/callum-oakley/jfn/releases/download/v${version}/jfn-${version}-macos.tar.gz" |
              shasum -a 256 | jfn '$.match(/[0-9a-f]{64}/)[0]'
          )"
          linux_sha256="$(
            curl -sfL "https://github.com/callum-oakley/jfn/releases/download/v${version}/jfn-${version}-linux.tar.gz" |
              shasum -a 256 | jfn '$.match(/[0-9a-f]{64}/)[0]'
          )"
          cat jfn.rb |
            version="${version}" macos_sha256="${macos_sha256}" linux_sha256="${linux_sha256}" jfn '
              $.replace(
                /(?<=version ")[^"]*(?=")/,
                $version,
              ).replace(
                /(?<=macos.tar.gz"\s+sha256 ")[^"]*(?=")/,
                $macos_sha256,
              ).replace(
                /(?<=linux.tar.gz"\s+sha256 ")[^"]*(?=")/,
                $linux_sha256,
              )
            ' > jfn.rb.new
          mv jfn.rb.new jfn.rb
      - run: git config --global user.name 'Callum Oakley'
      - run: git config --global user.email 'hello@callumoakley.net'
      - run: git commit -am 'jfn ${{ github.event.client_payload.version }}'
      - run: git push
